export const mappings = {
    "firstname": {
        "MyDataAttribute": "firstname",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n <{person}> a cco:Person;\n    cco:designated_by cco:PersonFullName_{guid} .\n\ncco:PersonFullName_{guid} a cco:PersonFullName;\n    <http://purl.obolibrary.org/obo/BFO_0000051> cco:PersonGivenName_{guid} .\n\ncco:PersonGivenName_{guid} a cco:PersonGivenName;\n        obo:RO_0010001 cco:InformationBearingEntity_PersonGivenName_{guid} .\n\ncco:InformationBearingEntity_PersonGivenName_{guid} a cco:InformationBearingEntity;\n    cco:has_text_value '{value}';\n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?PersonGivenNameIRI ?FirstName ?VerifiableCredential WHERE {\n        ?Person a cco:Person ;\n                cco:designated_by ?PersonFullName; .  \n\n        ?PersonFullName a cco:PersonFullName ;\n                <http://purl.obolibrary.org/obo/BFO_0000051> ?PersonGivenNameIRI .\n\n        ?PersonGivenNameIRI a cco:PersonGivenName ;\n                <http://purl.obolibrary.org/obo/RO_0010001>  ?PersonGivenNameIBE . \n\n        ?PersonGivenNameIBE cco:has_text_value ?FirstName;\n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential .   \n  }"
    },
    "lastname": {
        "MyDataAttribute": "lastname",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\n    cco:designated_by cco:PersonFullName_{guid}.\n\ncco:PersonFullName_{guid} a cco:PersonFullName ;\n    <http://purl.obolibrary.org/obo/BFO_0000051> cco:PersonFamilyName_{guid}.\n\ncco:PersonFamilyName_{guid} a cco:PersonFamilyName; \n    obo:RO_0010001 cco:InformationBearingEntity_PersonFamilyName_{guid} .\n\ncco:InformationBearingEntity_PersonFamilyName_{guid} a cco:InformationBearingEntity; \ncco:has_text_value '{value}'; \nobo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?PersonFamilyNameIRI ?LastName ?VerifiableCredential WHERE {\n        ?Person a cco:Person ;\n                cco:designated_by ?PersonFullName; . \n                        \n        ?PersonFullName a cco:PersonFullName ;\n                <http://purl.obolibrary.org/obo/BFO_0000051> ?PersonFamilyNameIRI.\n\n        ?PersonFamilyNameIRI a cco:PersonFamilyName ;\n                <http://purl.obolibrary.org/obo/RO_0010001> ?PersonFamilyNameIBE. \n\n        ?PersonFamilyNameIBE cco:has_text_value ?LastName ;\n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential .   \n  }"
    },
    "email": {
        "MyDataAttribute": "email",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/> \nPREFIX obo: <http://purl.obolibrary.org/obo/> \n\nINSERT DATA {\n<{person}> a cco:Person;\ncco:uses cco:EmailBox_{guid} .\n\ncco:EmailBox_{guid} a cco:EmailBox ;\n    obo:RO_0000056 cco:StasisOfTelecommunicationEndpointAssignment_{guid} .\n\ncco:StasisOfTelecommunicationEndpointAssignment_{guid} a cco:StasisOfTelecommunicationEndpointAssignment ;\n    obo:RO_0000057 cco:TelecommunicationEndpoint_{guid} .\n\ncco:TelecommunicationEndpoint_{guid} a cco:TelecommunicationEndpoint;\n    cco:designated_by cco:EmailAddress_{guid} .\n\ncco:EmailAddress_{guid} a cco:EmailAddress ;\n    obo:RO_0010001 cco:InformationBearingEntity_EmailAddress_{guid} .\n\ncco:InformationBearingEntity_EmailAddress_{guid} a cco:InformationBearingEntity ;\n    cco:has_text_value \"{value}\" ;\n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?VerifiableCredential ?EmailAddressIRI ?Email  WHERE {\n        ?Person a cco:Person ;\n                cco:uses ?EmailBox . \n\n        ?EmailBox a cco:EmailBox;\n                obo:RO_0000056 ?StasisOfTelecommunicationEndpointAssignment . \n\n        ?StasisOfTelecommunicationEndpointAssignment a cco:StasisOfTelecommunicationEndpointAssignment ; \n                obo:RO_0000057 ?TelecommunicationEndpoint . \n\n        ?TelecommunicationEndpoint a cco:TelecommunicationEndpoint ;\n                cco:designated_by ?EmailAddressIRI . \n\n        ?EmailAddressIRI a cco:EmailAddress;\n                obo:RO_0010001 ?EmailIBE .\n\n        ?EmailIBE cco:has_text_value ?Email ; \n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential .       \n        }"
    },
    "birthday": {
        "MyDataAttribute": "birthday",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\ncco:is_object_of cco:Birth_{guid} .\n\ncco:Birth_{guid} a cco:Birth ;\n    cco:occurs_on cco:Day_{guid} .\n\ncco:Day_{guid} a cco:Day ;\n    cco:designated_by cco:DateIdentifier_{guid} .\n\ncco:DateIdentifier_{guid} a cco:DateIdentifier ;\n    obo:RO_0010001 cco:InformationBearingEntity_DataIdentifier_{guid} .\n\ncco:InformationBearingEntity_DataIdentifier_{guid} a cco:InformationBearingEntity ;\n  cco:has_text_value \"{value}\";\n  obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?Person ?Birthday ?VerifiableCredential WHERE {\n        ?Person a cco:Person ;\n                cco:is_object_of ?Birth. \n\n        ?Birth a cco:Birth;\n                cco:occurs_on ?Birth_Day. \n\n        ?Birth_Day a cco:Day;\n                cco:designated_by ?DataIdentifier . \n\n        ?DataIdentifier <http://purl.obolibrary.org/obo/RO_0010001> ?DataIdentifierIBE . \n\n        ?DataIdentifierIBE  cco:has_text_value ?Birthday ;\n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential .\n  }"
    },
    "mailingStreetAddress": {
        "MyDataAttribute": "mailingStreetAddress",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person; \ncco:agent_in cco:ActOfResiding_{guid} . \n\ncco:ActOfResiding_{guid} a cco:ActOfResiding ; \n    obo:RO_0000057 cco:ResidentialFacility_{guid} . \n\ncco:ResidentialFacility_{guid} a cco:ResidentialFacility ; \n    cco:designated_by cco:StreetAdress_{guid} . \n    \ncco:StreetAdress_{guid} a cco:StreetAddress ; \n    obo:RO_0010001 cco:InformationBearingEntity_StreetAdress_{guid} . \n    \ncco:InformationBearingEntity_StreetAdress_{guid} a cco:InformationBearingEntity ; \n    cco:has_text_value \"{value}\"; \n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} . \n}",
        "ReadQuery": "SELECT ?VerifiableCredential ?StreetAdressIRI ?MailingStreet WHERE {\n        ?Person a cco:Person;\n                cco:agent_in ?ActOfResiding.\n\n        ?ActOfResiding a cco:ActOfResiding;\n                obo:RO_0000057 ?ResidentialFacility.\n\n        ?ResidentialFacility a cco:ResidentialFacility;\n                cco:designated_by ?StreetAdressIRI.\n\n        ?StreetAdressIRI a cco:StreetAddress;\n                obo:RO_0010001 ?StreetAdressIBE .\n\n        ?StreetAdressIBE a cco:InformationBearingEntity;\n                cco:has_text_value  ?MailingStreet ;\n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential . \n  }"
    },
    "mailingCity": {
        "MyDataAttribute": "mailingCity",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\ncco:agent_in cco:ActOfResiding_{guid} .\n\ncco:ActOfResiding_{guid} a cco:ActOfResiding ;\n    obo:RO_0000057 cco:ResidentialFacility_{guid} .\n    \ncco:ResidentialFacility_{guid} a cco:ResidentialFacility ;\n    obo:RO_0001025 cco:LocalAdministrativeRegion_{guid} .\n    \ncco:LocalAdministrativeRegion_{guid} a cco:LocalAdministrativeRegion ;\n    cco:designated_by cco:DesignativeName_{guid} .\n    \ncco:DesignativeName_{guid} a cco:DesignativeName ;\n    obo:RO_0010001 cco:InformationBearingEntity_DesignativeName_{guid} .\n    \ncco:InformationBearingEntity_DesignativeName_{guid} a cco:InformationBearingEntity ;\n    cco:has_text_value \"{value}\";\n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?VerifiableCredential ?CityIRI ?MailingCity WHERE \n        {\n          ?Person a cco:Person ;\n                          cco:agent_in ?ActOfResiding . \n  \n          ?ActOfResiding a cco:ActOfResiding ; \n                                         obo:RO_0000057 ?ResidentialFacility. \n          ?ResidentialFacility a cco:ResidentialFacility;\n                                                   obo:RO_0001025 ?CityIRI. \n  \n          # Admin Region\n          ?CityIRI a cco:LocalAdministrativeRegion ; \n                           cco:designated_by ?LocalAdminRegion1DesName . \n          #City \n          ?LocalAdminRegion1DesName a cco:DesignativeName;\n                                                                obo:RO_0010001  ?LocalAdminRegion1DesNameIBE. \n  \n          ?LocalAdminRegion1DesNameIBE cco:has_text_value ?MailingCity ;\n                                                                   obo:BFO_0000050 ?VerifiableCredentialIRI. \n  \n          ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n  \n          ?VerifiableCredential_desc a cco:DesignativeName ; \n                                                                 cco:has_text_value ?VerifiableCredential . \n  }"
    },
    "mailingState": {
        "MyDataAttribute": "mailingState",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\ncco:agent_in cco:ActOfResiding_{guid} .\n\ncco:ActOfResiding_{guid} a cco:ActOfResiding ;\n    obo:RO_0000057 cco:ResidentialFacility_{guid} .\n    \ncco:ResidentialFacility_{guid} a cco:ResidentialFacility ;\n    obo:RO_0001025 cco:LocalAdministrativeRegion_{guid} .\n    \ncco:LocalAdministrativeRegion_{guid} a cco:LocalAdministrativeRegion ;\n    obo:BFO_0000050 cco:FirstOrderAdministrativeRegion_{guid} .\n    \ncco:FirstOrderAdministrativeRegion_{guid} a cco:State ;\n    cco:designated_by cco:DesignativeName_{guid} .\n    \ncco:DesignativeName_{guid} a cco:DesignativeName ;\n    obo:RO_0010001 cco:InformationBearingEntity_DesignativeName_{guid} .\n    \ncco:InformationBearingEntity_DesignativeName_{guid} a cco:InformationBearingEntity ;\ncco:has_text_value \"{value}\";\nobo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?VerifiableCredential ?StateIRI ?MailingState WHERE {\n        ?Person a cco:Person ;\n                cco:agent_in ?ActOfResiding . \n\n        ?ActOfResiding a cco:ActOfResiding ; \n                obo:RO_0000057 ?ResidentialFacility. \n\n        ?ResidentialFacility a cco:ResidentialFacility;\n                <http://purl.obolibrary.org/obo/RO_0001025> ?LocalAdminRegion1. \n\n        ?LocalAdminRegion1 a cco:LocalAdministrativeRegion ; \n                <http://purl.obolibrary.org/obo/BFO_0000050> ?StateIRI . \n\n        ?StateIRI a cco:State ; \n                cco:designated_by ?LocalAdminRegion1StateCityDesc. \n\n        ?LocalAdminRegion1StateCityDesc a cco:DesignativeName ; \n                <http://purl.obolibrary.org/obo/RO_0010001>   ?LocalAdminRegion1StateCityDescIBE . \n\n        ?LocalAdminRegion1StateCityDescIBE a cco:InformationBearingEntity ;\n                cco:has_text_value ?MailingState;\n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential .                                                        \n        }"
    },
    "mailingPostalCode": {
        "MyDataAttribute": "mailingPostalCode",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\ncco:agent_in cco:ActOfResiding_{guid} .\n\ncco:ActOfResiding_{guid} a cco:ActOfResiding ;\n    obo:RO_0000057 cco:ResidentialFacility_{guid} .\n    \ncco:ResidentialFacility_{guid} a cco:ResidentialFacility ;\n  obo:RO_0001025 cco:PostalZone_{guid} .\n  \ncco:PostalZone_{guid} a cco:PostalZone ;\n    cco:designated_by cco:PostalCode_{guid} .\n    \ncco:PostalCode_{guid} a cco:PostalCode ;\n    obo:RO_0010001 cco:InformationBearingEntity_PostalCode_{guid} .\n    \ncco:InformationBearingEntity_PostalCode_{guid} a cco:InformationBearingEntity ;\n    cco:has_text_value \"{value}\";\n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?VerifiableCredential?PostalCodeIRI ?MailingPostCode WHERE {\n        ?Person a cco:Person;\n                cco:agent_in ?ActOfResiding.\n\n        ?ActOfResiding a cco:ActOfResiding;\n                obo:RO_0000057 ?ResidentialFacility.\n\n        ?ResidentialFacility a cco:ResidentialFacility;\n                obo:RO_0001025 ?PostalZone . \n\n        ?PostalZone a cco:PostalZone;\n                cco:designated_by ?PostalCodeIRI.\n\n        ?PostalCodeIRI a cco:PostalCode;\n                obo:RO_0010001 ?PostalCodeIBE.\n\n        ?PostalCodeIBE a cco:InformationBearingEntity;\n                cco:has_text_value ?MailingPostCode;\n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential . \n        }"
    },
    "mailingCountry": {
        "MyDataAttribute": "mailingCountry",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\ncco:agent_in cco:ActOfResiding_{guid} .\n\ncco:ActOfResiding_{guid} a cco:ActOfResiding ;\n    obo:RO_0000057 cco:ResidentialFacility_{guid} .\n    \ncco:ResidentialFacility_{guid} a cco:ResidentialFacility ;\n    obo:RO_0001025 cco:LocalAdministrativeRegion_{guid} .\n    \n    cco:LocalAdministrativeRegion_{guid} a cco:LocalAdministrativeRegion ;\n     obo:BFO_0000050 cco:FirstOrderAdministrativeRegion_{guid} .\n     \ncco:FirstOrderAdministrativeRegion_{guid} a cco:State ;\n    obo:BFO_0000050 cco:County_{guid} .\n    \ncco:County_{guid} a cco:Country ;\n    cco:designated_by cco:PostalCodeDesignativeName_{guid} .\n    \ncco:PostalCodeDesignativeName_{guid} a cco:DesignativeName ;\n    obo:RO_0010001 cco:InformationBearingEntity_DesignativeName_{guid} .\n    \ncco:InformationBearingEntity_DesignativeName_{guid} a cco:InformationBearingEntity ;\n    cco:has_text_value \"{value}\";\n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?VerifiableCredential ?CountryIRI ?MailingCountry WHERE {\n        ?Person a cco:Person ;\n                cco:agent_in ?ActOfResiding . \n\n        ?ActOfResiding a cco:ActOfResiding ; \n                obo:RO_0000057 ?ResidentialFacility. \n                \n        ?ResidentialFacility a cco:ResidentialFacility;\n                <http://purl.obolibrary.org/obo/RO_0001025> ?LocalAdminRegion1. \n\n        ?LocalAdminRegion1 a cco:LocalAdministrativeRegion ; \n                <http://purl.obolibrary.org/obo/BFO_0000050> ?LocalAdminRegion1StateCity . \n\n        ?LocalAdminRegion1StateCity a cco:State ; \n                <http://purl.obolibrary.org/obo/BFO_0000050>  ?CountryIRI. \n        \n        ?CountryIRI a cco:Country ; \n                cco:designated_by ?CountryDesc  . \n\n        ?CountryDesc a cco:DesignativeName ; \n                <http://purl.obolibrary.org/obo/RO_0010001> ?CountryDescIBE .  \n\n        ?CountryDescIBE cco:has_text_value ?MailingCountry;\n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential .\n                  \n    }"
    },
    "homePhoneNumber": {
        "MyDataAttribute": "homePhoneNumber",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n <{person}> a cco:Person;\ncco:user cco:LandlineTelephone_{guid} .\n\ncco:LandlineTelephone_{guid} a cco:LandlineTelephone;\n    obo:RO_0000056 cco:StasisOfTelecommunicationEndpointAssignment_{guid} .\n    \ncco:StasisOfTelecommunicationEndpointAssignment_{guid} a  cco:StasisOfTelecommunicationEndpointAssignment;\n    obo:RO_0000057 cco:TelecommunicationEndpoint_{guid} .\n    \ncco:TelecommunicationEndpoint_{guid} a cco:TelecommunicationEndpoint ;\n    cco:designated_by cco:TelephoneNumber_{guid} .\n    \ncco:TelephoneNumber_{guid} a cco:TelephoneNumber ;\n    obo:RO_0010001 cco:InformationBearingEntity_TelephoneNumber_{guid} .\n    \ncco:InformationBearingEntity_TelephoneNumber_{guid} a cco:InformationBearingEntity ;\n    cco:has_text_value \"{value}\";\n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": ""
    },
    "mobilePhoneNumber": {
        "MyDataAttribute": "mobilePhoneNumber",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\ncco:user cco:MobileTelephone_{guid} .\n\ncco:MobileTelephone_{guid} a cco:MobileTelephone;\n    obo:RO_0000056 cco:StasisOfTelecommunicationEndpointAssignment_{guid} .\n    \ncco:StasisOfTelecommunicationEndpointAssignment_{guid} a  cco:StasisOfTelecommunicationEndpointAssignment;\n    obo:RO_0000057 cco:TelecommunicationEndpoint_{guid} .\n    \ncco:TelecommunicationEndpoint_{guid} a cco:TelecommunicationEndpoint ;\n    cco:designated_by cco:TelephoneNumber_{guid} .\n    \ncco:TelephoneNumber_{guid} a cco:TelephoneNumber ;\n    obo:RO_0010001 cco:InformationBearingEntity_TelephoneNumber_{guid} .\n    \ncco:InformationBearingEntity_TelephoneNumber_{guid} a cco:InformationBearingEntity ;\n    cco:has_text_value \"{value}\";\n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": ""
    },
    "employerName": {
        "MyDataAttribute": "employerName",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\nobo:RO_0000053 cco:OccupationRole_{guid} .\n\ncco:OccupationRole_{guid} a cco:OccupationRole;\n    cco:has_organization_context cco:Organization_{guid} .\n    \ncco:Organization_{guid} a cco:Organization ;\n    cco:designated_by cco:DesignativeName_{guid}.\n    \ncco:DesignativeName_{guid} a cco:DesignativeName ;\n    obo:RO_0010001 cco:InformationBearingEntity_DesignativeName_{guid} .\n    \ncco:InformationBearingEntity_DesignativeName_{guid} a cco:InformationBearingEntity ;\n  cco:has_text_value \"{value}\";\n  obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": ""
    },
    "employeeTitle": {
        "MyDataAttribute": "employeeTitle",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person;\nobo:RO_0000053 cco:OccupationRole_{guid} .\n\ncco:OccupationRole_{guid} a cco:OccupationRole;\n    cco:described_by cco:NominalMeasurementInformationContentEntity_{guid} .\n    \ncco:NominalMeasurementInformationContentEntity_{guid} a cco:NominalMeasurementInformationContentEntity;\n    obo:RO_0010001 cco:InformationBearingEntity_NominalMeasurementInformationContentEntity_{guid} .\n    \ncco:InformationBearingEntity_NominalMeasurementInformationContentEntity_{guid} a cco:InformationBearingEntity ;\n  cco:has_text_value \"{value}\";\n  obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": ""
    },
    "weight": {
        "MyDataAttribute": "weight",
        "CreateQuery": "PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>\nPREFIX obo: <http://purl.obolibrary.org/obo/>\n       \nINSERT DATA\n{ \n<{person}> a cco:Person ;\n  cco:has_quality <http://www.ontologyrepository.com/CommonCoreOntologies/Quality-Weight-{guid}> .\n\n<http://www.ontologyrepository.com/CommonCoreOntologies/Quality-Weight-{guid}> a cco:Weight ; \n    cco:is_measured_by <http://www.ontologyrepository.com/CommonCoreOntologies/{guid}-Quality-Weight-MeasuredICE> .\n\n<http://www.ontologyrepository.com/CommonCoreOntologies/{guid}-Quality-Weight-MeasuredICE>  a cco:MeasurementInformationContentEntity;\nobo: RO_0000056 <http://www.ontologyrepository.com/CommonCoreOntologies/{guid}-Quality-Weight-MeasuredIBE> . \n\n<http://www.ontologyrepository.com/CommonCoreOntologies/{guid}-Quality-Weight-MeasuredIBE>  a cco:InformationBearingEntity ; \n    cco:has_text_value \"{value}\"; \n    obo:BFO_0000050 cco:VerifiableCredential_{verfiableCredentialId} .\n}",
        "ReadQuery": "SELECT ?VerifiableCredential ?WeightIRI ?Weight WHERE {\n        ?Person a cco:Person;\n                cco:has_quality ?WeightQuality . \n\n        ?WeightQuality a cco:Weight;\n                cco:is_measured_by ?WeightQualityICE .    \n\n        ?WeightQualityICE obo:RO_0000056 ?WeightIRI . \n\n        ?WeightIRI  cco:has_text_value ?Weight ; \n                obo:BFO_0000050 ?VerifiableCredentialIRI. \n\n        ?VerifiableCredentialIRI cco:designated_by ?VerifiableCredential_desc . \n\n        ?VerifiableCredential_desc a cco:DesignativeName ; \n                cco:has_text_value ?VerifiableCredential .                \n        }"
    }
}